algoritmo "seu nome"
var
   nome: caractere
inicio
      escreva ("Escreva seu nick: ")
      leia (nome)
      escreval ("------------------------------------------")
      escreval ("        --- Olá ", nome, " ---")
      escreval ("------------------------------------------")
      escreval ("---         Bem-Vindo ao Tibia         ---")
      escreval ("------------------------------------------")
fimalgoritmo
